// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResp struct {
	Flag bool `json:"flag"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Flag bool `json:"flag"`
}
